name: Simple Build OpenWRT for Xiaomi Mi Router 4 with Custom Packages

on:
  #手动运行
  workflow_dispatch:
  #文件修改时触发
  push:
    branches:
      - main
    # 添加路径过滤，仅当当前工作流文件被修改时触发
    paths:
      - .github/workflows/SimpleBuildOpenWRT_Official.yml  # 需替换为当前工作流文件的实际路径
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 10240
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
      - name: Checkout OpenWRT
        uses: actions/checkout@v4
        with:
          repository: openwrt/openwrt
          ref: master

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses5-dev gawk git libssl-dev gettext zlib1g-dev swig rsync

      - name: Clone OpenClash
        run: git clone https://github.com/vernesong/OpenClash.git package/luci-app-openclash

      - name: Clone Passwall2
        run: git clone https://github.com/xiaorouji/openwrt-passwall2.git package/passwall2

      - name: Create seed.config
        run: |
          cat << EOF > seed.config
          CONFIG_TARGET_ramips=y
          CONFIG_TARGET_ramips_mt7621=y
          CONFIG_TARGET_ramips_mt7621_DEVICE_xiaomi_mi-router-4=y
          CONFIG_PACKAGE_luci=y
          CONFIG_PACKAGE_luci-app-openclash=y
          CONFIG_PACKAGE_luci-app-passwall2=y
          CONFIG_PACKAGE_wpad-mesh=y
          # CONFIG_PACKAGE_wpad-basic is not set
          EOF

      - name: Apply configuration
        run: |
          cp seed.config .config
          make defconfig

      - name: Build firmware
        id: build
        run: make -j$(nproc) V=s || make -j1 V=s > compile.log 2>&1
        
      - name: 查看报错日志
        if: always()
        run: |
          LOG_FILE='compile.log'
          # 错误处理：动态截取倒数第二个 Entering directory 到错误行
          echo "=== 从倒数第二个目录入口到日志结尾 ==="
          tac "$LOG_FILE" | awk '
              /Entering directory/ { 
                  entry_count++
                  if (entry_count == 2) { 
                      print "----- 倒数第二个目录入口 -----"
                      print $0
                      print "============================="
                      buffer = $0 "\n" buffer
                      next
                  }
              }
              { 
                  buffer = $0 "\n" buffer 
              }
              END { 
                  print buffer 
              }
          ' 
# | tac 少一次反转试试
      - name: 直接tail试试
        if: always()
        run: ｜
          tail -300 compile.log

      - name: Upload firmware
        if: steps.build.conclusion == 'success'
        uses: actions/upload-artifact@master
        with:
          name: openwrt-firmware
          path: bin/targets/ramips/mt7621/*
