name: Simple Build OpenWRT for Xiaomi Mi Router 4 with Custom Packages

on:
  #手动运行
  workflow_dispatch:
  #文件修改时触发
  push:
    branches:
      - main
    # 添加路径过滤，仅当当前工作流文件被修改时触发
    paths:
      - .github/workflows/SimpleBuildOpenWRT_Official.yml  # 需替换为当前工作流文件的实际路径
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 10240
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
      - name: Checkout Self Repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: master
          path: $GITHUB_WORKSPACE
          
      - name: Checkout OpenWRT.org_Official
        uses: actions/checkout@v4
        with:
          repository: openwrt/openwrt
          ref: master
          path: openwrt

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses5-dev gawk git libssl-dev gettext zlib1g-dev swig rsync ruby unzip libpam0g-dev libcurl4-openssl-dev libdeflate-dev
          
      - name: Update feeds
        run: |
          cd openwrt
          echo 'src-git passwall https://github.com/xiaorouji/openwrt-passwall' >>feeds.conf.default
          echo 'src-git OpenClash https://github.com/vernesong/OpenClash' >>feeds.conf.default
          echo 'src-git small8 https://github.com/kenzok8/small-package' >>feeds.conf.default
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          
      - name: Apply patch to trojan-plus
        run: |
          cd openwrt
          cd feeds/small8/trojan-plus
          patch -p1 < ../../../trojan-plus.patch  # 假设补丁文件位于仓库根目录

      - name: Create seed.config
        run: |
          cd openwrt
          cat << EOF > seed.config
          CONFIG_TARGET_ramips=y
          CONFIG_TARGET_ramips_mt7621=y
          CONFIG_TARGET_ramips_mt7621_DEVICE_xiaomi_mi-router-4=y
          CONFIG_PACKAGE_luci=y
          CONFIG_PACKAGE_luci-app-openclash=y
          CONFIG_PACKAGE_luci-app-passwall=y
          CONFIG_PACKAGE_wpad-mesh=y
          CONFIG_PACKAGE_luci-lib-base=y
          CONFIG_PACKAGE_luci-lib-ipkg=y
          CONFIG_PACKAGE_ruby=y
          CONFIG_PACKAGE_bash=y
          CONFIG_PACKAGE_tcping=y
          CONFIG_PACKAGE_geoview=y
          # CONFIG_PACKAGE_wpad-basic is not set
          EOF
          
      - name: Apply configuration
        run: |
          cd openwrt
          cp seed.config .config
          make defconfig
          sed -i -e 's/^CONFIG_TOOLS_LIBCRYPTO=y$/CONFIG_TOOLS_LIBCRYPTO=n/' -e 's/^CONFIG_FIT_SIGNATURE=y$/CONFIG_FIT_SIGNATURE=n/' .config


      - name: Build firmware
        id: build
        run: |
          cd openwrt
          make -j$(nproc) tools/install  V=s || make -j1 tools/install  V=s
          make -j$(nproc) toolchain/install  V=s || make -j1 toolchain/install  V=s
          make -j$(nproc) package/feeds/luci/luci-base/compile V=s || make -j$(nproc) package/luci/modules/luci-base/compile V=s || make -j1 package/feeds/luci/luci-base/compile V=s || make -j1 package/luci/modules/luci-base/compile V=s
          make -j$(nproc) V=s || make -j1 V=s > compile.log 2>&1
        
      - name: 查看报错日志
        if: always()
        run: |
          cd openwrt
          LOG_FILE='compile.log'
          # 错误处理：动态截取倒数第二个 Entering directory 到错误行
          echo "=== 从倒数第二个目录入口到日志结尾 ==="
          tac "$LOG_FILE" | awk '
              /Entering directory/ { 
                  entry_count++
                  if (entry_count == 2) { 
                      print "----- 倒数第二个目录入口 -----"
                      print $0
                      print "============================="
                      buffer = $0 "\n" buffer
                      next
                  }
              }
              { 
                  buffer = $0 "\n" buffer 
              }
              END { 
                  print buffer 
              }
          ' 
# | tac 少一次反转试试
      - name: 直接tail试试
        if: always()
        run: |
          cd openwrt
          tail -300 compile.log

      - name: Upload firmware
        if: steps.build.conclusion == 'success'
        uses: actions/upload-artifact@master
        with:
          name: openwrt-firmware
          path: openwrt/bin/targets/ramips/mt7621/*
