name: test_upload_to_MEGA.yml
on:
  push:
    branches:
      - main
      - master
    paths:
      - .github/workflows/test_upload_to_MEGA.yml
  workflow_dispatch:


env:
  ACTIONS_STEP_DEBUG: true
  SOURCE: coolsnowwolf

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      

      - name: Checkout
        uses: actions/checkout@main
      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get -qq update
          sudo apt -y install python3-pip
          pip install mega.py || pip3 install mega.py || exit 1
          
      - name: 生成测试文件
        run: |
          mkdir openwrt
          tar -cf - openwrt/ | pigz > ${{ env.SOURCE }}.tar.gz
          pwd && ls
          
      - name: Upload to MEGA
        env:
          MEGA_USERNAME: ${{ secrets.MEGA_USERNAME }}  # 从 Secrets 中获取用户名
          MEGA_PASSWORD: ${{ secrets.MEGA_PASSWORD }}  # 从 Secrets 中获取密码
        run: |
          python upload_to_MEGA.py
